# Generated by Django 5.0.6 on 2024-06-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websitepage',
            old_name='active',
            new_name='is_active',
        ),
    ]
