# Generated by Django 5.0.6 on 2024-06-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
